import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const interVF = localFont({
  src: "./fonts/intervf.ttf",
  variable: "--font-inter",
  weight: "100 200 300 400 500 600 700 800 900",
});

const spaceGroteskVF = localFont({
  src: "./fonts/spacegrotsekvf.ttf",
  variable: "--font-space-grotesk",
  weight: "300 400 500 600 700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interVF.className} ${spaceGroteskVF.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
